cam_width:  640
cam_height: 480
cam_fx: 462.266357421875
cam_fy: 462.266357421875
cam_cx: 320.0
cam_cy: 240.0

# 相机外参配置
cam2body_R: [ 0.0, -1.0, 0.0, 
              0.0, 0.0, -1.0, 
              1.0, 0.0, 0.0] # 3x3 旋转矩阵 (行优先)
cam2body_p: [0.14, 0.0, -0.02]                             # 平移向量 (X, Y, Z)，单位：米