%YAML 1.0
---

# common parameters

# support: 1 imu 1 cam; 1 imu 2 cam: 2 cam;
imu: 1         
num_of_cam: 2  # Number of cameras

imu_topic: "/mavros/imu/data_raw"
image0_topic: "/d435i/infra1/image_raw"
image1_topic: "/d435i/infra2/image_raw"

output_path: "/home/cq/Elastic-Tracker-Drone/src/VINS-Fusion/output/gazebo"

cam0_calib: "left_gazebo.yaml"
cam1_calib: "right_gazebo.yaml"
image_width: 640
image_height: 480

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0 means accurate extrinsic parameters are trusted, 1 means initial guess for extrinsic parameters is provided and will be optimized.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -3.0597105734349483e-02, -5.8927835241659454e-03,
       9.9951442822153336e-01, 4.7302157421591003e-02,
       -9.9953144626651969e-01, -6.5966180705956390e-04,
       -3.0601515822913872e-02, 2.2936545354189812e-02,
       8.3966960215819952e-04, -9.9998241981978775e-01,
       -5.8698386963857985e-03, 6.1639590858913150e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -3.0069515759978849e-02, -5.7183785193311576e-03,
       9.9953145241611607e-01, 4.4848038940723180e-02,
       -9.9954744323873812e-01, -6.8446400583832556e-04,
       -3.0073912680706472e-02, -2.7107742793766636e-02,
       8.5611731814760894e-04, -9.9998341569054772e-01,
       -5.6952091272584049e-03, 6.1794907739113121e-02, 0., 0., 0., 1. ]
   
# Multiple thread support
multiple_thread: 1

# Feature tracker parameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequency (Hz) of publish tracking result. At least 10Hz for good estimation. If set to 0, the frequency will be the same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

# Optimization parameters
max_solver_time: 0.04  # max solver iteration time (ms), to guarantee real-time
max_num_iterations: 8   # max solver iterations, to guarantee real-time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

# IMU parameters (The more accurate parameters you provide, the better performance)
acc_n: 0.1          # accelerometer measurement noise standard deviation
gyr_n: 0.01         # gyroscope measurement noise standard deviation
acc_w: 0.001        # accelerometer bias random walk noise standard deviation
gyr_w: 0.0001       # gyroscope bias random walk noise standard deviation
g_norm: 9.805        # gravity magnitude

# Unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.1                             # initial value of time offset. unit: s. read image clock + td = real image clock (IMU clock)

# Loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/fast/savedfiles/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization purposes; you can turn this off by setting to 0


